In [2]:
import numpy as np
# 1
print(np.__version__)

1.24.3


In [4]:
# 2
array1 = np.arange(10)

print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
# 3
array2 = np.full((3,3),True,dtype=bool)

print(array2)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [10]:
# 4
array3 = np.array([1,2,3,4,5,6,7,8,9])
print(array3[(array3%2)!=0])

[1 3 5 7 9]


In [23]:
# 5
array4 = np.array([0,1,2,3,4,5,6,7,8,9])
print(array4)
array4[array4 % 2 != 0] = -1
print(array4)



[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [13]:
# 6
array5 = np.array([0,1,2,3,4,5,6,7,8,9])
out = np.where(array5 % 2 != 0,-1,array5)

print(array5)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [22]:
# 7
array6 = np.arange(10)
print(array6)
print(array6.reshape(2,5))
print(array6.reshape(2,-1)) #con -1 calcula automaticamente el tamaño de la otra dimension en funcion de la cantidad de elementos de la lista original


[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [36]:
# 8
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

print(np.concatenate([a,b], axis=0))
print(np.vstack([a,b]))
print(np.r_[a,b])



[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [52]:
# 9
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

print(np.concatenate([a,b], axis=1))
print(np.hstack([a,b]))
print(np.c_[a,b])

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [53]:
# 10
a = np.array([1,2,3])
print(np.concatenate([np.repeat(a,3),np.tile(a,3)], axis=0))

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [55]:
# 11
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(np.intersect1d(a,b))

[2 4]


In [57]:
# 12
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

print(np.setdiff1d(a,b))
print(a)
print(b)

[1 2 3 4]
[1 2 3 4 5]
[5 6 7 8 9]


In [59]:
# 13
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(np.where(a == b))

(array([1, 3, 5, 7], dtype=int64),)


In [67]:
# 14
a = np.array([2, 6, 1, 9, 10, 3, 27])

print(a[np.where((a>=5) & (a <=10))])
print(a[(a>=5) & (a <=10)])
print(a[np.where(np.logical_and(a>=5,a <=10))])

[ 6  9 10]
[ 6  9 10]
[ 6  9 10]


In [68]:
# 15
def maxx(x, y):
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

print(pair_max(a,b))

[6. 7. 9. 8. 9. 7. 5.]


In [74]:
# 16
arr = np.arange(9).reshape(3,3)
print(arr)
# opcion 1, no modifica la original
print(arr[:,[1,0,2]])
# opcion 2, modifica la original
arr[:,[0,1]] = arr[:,[1,0]]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [77]:
# 17
arr = np.arange(9).reshape(3,3)
print(arr)
# opcion 1, no modifica la original
print(arr[[1,0,2],:])
# opcion 2, modifica la original
arr[[0,1],:] = arr[[1,0],:]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [86]:
# 18
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[::-1,:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [88]:
# 19
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[:,::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [91]:
# 20
arr = np.random.uniform(5,10, (5,3))
arr

array([[5.36827262, 6.2210228 , 5.03812468],
       [7.19932438, 5.92470504, 5.79907932],
       [6.91491502, 6.34102325, 7.46399994],
       [6.16444101, 6.09971934, 9.51080276],
       [5.60918168, 5.71102348, 8.04076318]])

In [132]:
# 21
rand_arr = np.random.random((5,3))
print(np.trunc(rand_arr*1000)/1000)
# np.set_printoptions(precision=3)
# print(rand_arr)


[[0.578 0.62  0.944]
 [0.984 0.387 0.026]
 [0.17  0.045 0.031]
 [0.255 0.973 0.083]
 [0.23  0.689 0.496]]
[[0.579 0.621 0.945]
 [0.985 0.387 0.026]
 [0.17  0.045 0.032]
 [0.256 0.974 0.083]
 [0.231 0.69  0.497]]
[[0.579 0.621 0.945]
 [0.985 0.387 0.026]
 [0.17  0.045 0.032]
 [0.256 0.974 0.083]
 [0.231 0.69  0.497]]


In [5]:
# 22
np.set_printoptions(suppress=False)
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3

print(rand_arr)
np.set_printoptions(suppress=True,precision=6)
print(rand_arr)


[[5.43404942e-04 2.78369385e-04 4.24517591e-04]
 [8.44776132e-04 4.71885619e-06 1.21569121e-04]
 [6.70749085e-04 8.25852755e-04 1.36706590e-04]]
[[0.000543 0.000278 0.000425]
 [0.000845 0.000005 0.000122]
 [0.000671 0.000826 0.000137]]


In [6]:
# 23
a = np.arange(15)
np.set_printoptions(threshold=6)
print(a)

[ 0  1  2 ... 12 13 14]


In [14]:
# 24
import sys
np.set_printoptions(threshold=6)
a = np.arange(15)
np.set_printoptions(threshold=sys.maxsize)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
# 25
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=object)

print(iris_1d[:3])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']]


In [17]:
# 26
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

print(iris_1d[:3])

[(5.1, 3.5, 1.4, 0.2, b'Iris-setosa') (4.9, 3. , 1.4, 0.2, b'Iris-setosa')
 (4.7, 3.2, 1.3, 0.2, b'Iris-setosa')]


C:\Users\f_cof\AppData\Local\Temp\ipykernel_18660\2623597759.py:3: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)


In [21]:
# 27
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
print(iris_2d[:4])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]


In [22]:
# 28
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mu, med, sd)

5.843333333333334 5.8 0.8253012917851409


In [ ]:
# 29

In [ ]:
# 30