# Práctica Clase 3

## Numpy

**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.
* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.
* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.

In [3]:
import numpy as np

In [4]:
lista = [1, 2, 3, 4, 5, 6]

In [5]:
array = np.array([1, 2, 3, 4, 5, 6])

In [6]:
lista[2]

3

In [7]:
array[2]

3

In [8]:
lista[:3]

[1, 2, 3]

In [9]:
array[:3]

array([1, 2, 3])

In [10]:
lista[::-1]

[6, 5, 4, 3, 2, 1]

In [11]:
array[::-1]

array([6, 5, 4, 3, 2, 1])

In [12]:
sum(lista)

21

In [13]:
np.sum(array)

21

In [14]:
lista

[1, 2, 3, 4, 5, 6]

In [16]:
lista.append(7)

In [17]:
lista

[1, 2, 3, 4, 5, 6, 7]

In [20]:
array = np.append(array, 7)

In [21]:
array

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
array[0]

1

In [33]:
array[0] = 1

In [34]:
array

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
tupla = (1, 2, 3, 4, 5, 6)

In [29]:
tupla

(1, 2, 3, 4, 5, 6)

In [31]:
tupla[0]

1

In [35]:
tupla[0] = 10

TypeError: 'tuple' object does not support item assignment

In [38]:
for i in range(8, 11):
    array = np.append(array, i)

In [42]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
lista

[1, 2, 3, 4, 5, 6, 7]

In [40]:
max(lista)

7

In [41]:
min(lista)

1

In [44]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
np.max(array)

10

In [46]:
np.min(array)

1

¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.

In [48]:
lista

[1, 2, 3, 4, 5, 6, 7]

In [49]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
array + 3

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [51]:
lista + 3

TypeError: can only concatenate list (not "int") to list

In [52]:
[i + 3 for i in lista]

[4, 5, 6, 7, 8, 9, 10]

In [54]:
array * 5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [56]:
print(lista * 5)

[1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7]


In [57]:
np.random.randint(1, 10, 30)

array([8, 2, 8, 3, 6, 6, 2, 3, 1, 9, 6, 8, 4, 9, 2, 4, 5, 3, 1, 9, 5, 9,
       4, 3, 3, 1, 9, 7, 9, 8])

In [60]:
import random

In [65]:
lista_2 = []
for i in range(30):
    num = random.randint(1,9)
    lista_2.append(num)

In [66]:
print(lista_2)

[5, 6, 3, 2, 8, 1, 9, 4, 7, 7, 1, 9, 6, 4, 6, 3, 7, 9, 9, 2, 8, 9, 8, 7, 1, 4, 4, 9, 5, 4]


¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

In [70]:
# Para n = 6
vector = np.array([1, 2, 3, 4, 5, 6])

In [71]:
vector.shape

(6,)

In [77]:
vector_2 = np.array([[1], [2], [3], [4], [5], [6]])

In [78]:
vector_2

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [74]:
vector_2.shape

(6, 1)

In [79]:
vector_3 = np.array([[1, 2, 3, 4, 5, 6]])

In [80]:
vector_3

array([[1, 2, 3, 4, 5, 6]])

In [81]:
vector_3.shape

(1, 6)

In [83]:
tensor = np.array([ [ [1], [2] ], [ [3], [4] ] ])

In [84]:
tensor.shape

(2, 2, 1)

**Ejercicio 2**:
* Escribir un arreglo con números enteros del 0 al 9. Pista: arange
* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

In [86]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
range(0, 10)

range(0, 10)

In [90]:
intervalos = np.linspace(0, 9, 100)

intervalos

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        , 1.09090909, 1.18181818, 1.27272727,
       1.36363636, 1.45454545, 1.54545455, 1.63636364, 1.72727273,
       1.81818182, 1.90909091, 2.        , 2.09090909, 2.18181818,
       2.27272727, 2.36363636, 2.45454545, 2.54545455, 2.63636364,
       2.72727273, 2.81818182, 2.90909091, 3.        , 3.09090909,
       3.18181818, 3.27272727, 3.36363636, 3.45454545, 3.54545455,
       3.63636364, 3.72727273, 3.81818182, 3.90909091, 4.        ,
       4.09090909, 4.18181818, 4.27272727, 4.36363636, 4.45454545,
       4.54545455, 4.63636364, 4.72727273, 4.81818182, 4.90909091,
       5.        , 5.09090909, 5.18181818, 5.27272727, 5.36363636,
       5.45454545, 5.54545455, 5.63636364, 5.72727273, 5.81818182,
       5.90909091, 6.        , 6.09090909, 6.18181818, 6.27272727,
       6.36363636, 6.45454545, 6.54545455, 6.63636364, 6.72727

In [92]:
intervalos.shape

(100,)

**Ejercicio 3**:
* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son divisibles por 3<br>
Pista: mask

In [95]:
arreglo = np.arange(10, 101)
print(arreglo)

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


In [99]:
mascara = (arreglo % 3 == 0)

In [100]:
mascara

array([False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False])

In [101]:
arreglo[mascara]

array([12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60,
       63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

**Ejercicio 4**:
* Crear un arreglo de ceros de `shape` (5,10).
* Reemplazar la segunda y cuarta fila con unos
* Reemplazar la tercera y octava columna con dos (2).

In [104]:
ceros = np.zeros((5, 10), dtype=np.int32)

In [105]:
ceros

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [110]:
ceros[[1, 3]] = 1

In [111]:
ceros

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [119]:
ceros[:, [2, 7]] = 2

In [123]:
ceros

array([[0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
       [1, 1, 2, 1, 1, 1, 1, 2, 1, 1],
       [0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
       [1, 1, 2, 1, 1, 1, 1, 2, 1, 1],
       [0, 0, 2, 0, 0, 0, 0, 2, 0, 0]])

In [139]:
matriz = np.arange(1, 101).reshape((10,10))

In [140]:
matriz

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [146]:
matriz[2:7:3, 3:8:3]

array([[24, 27],
       [54, 57]])

In [137]:
lista_vacia = np.array([])

In [138]:
np.append(lista_vacia, 10)

array([10.])

**Ejercicio $\infty$**:
Hacer todos los ejercicios que puedan del siguiente link https://www.machinelearningplus.com/python/101-numpy-exercises-python/

O de https://github.com/rougier/numpy-100

Para explorar las funciones de creación de datos aleatorios:
https://numpy.org/doc/stable/reference/random/legacy.html