IMPORTACION DE LIBRERIA

In [2]:
import numpy as np
#Version de la libreria NUMPY
print(np.__version__)

1.24.3


CREACION DE ARRAYS

In [2]:
#From Lista
lista1 = [0,1,2,3,4,5,6]
array1 = np.array(lista1)
print(array1)

[0 1 2 3 4 5 6]


In [14]:
#from Rango o Secuencias
array2 = np.arange(start=2, stop=10,step=2)
print(array2)

#separacion equidistante con extremos inclusivos, dtype es Float por defecto
array3 = np.linspace(start=2, stop=10,num=8)
print(array3)

[2 4 6 8]
[ 2  3  4  5  6  7  8 10]


In [27]:
#Arrays Predefinidos
lista2 = [[1,2,3],[4,5,6]]

# Zeros: Inicializa con 0
print("Zeroes")
array4 = np.zeros((3,3), dtype = int)
print(array4)

array5 = np.zeros_like(lista2)
print(array5)

array6 = np.zeros(shape=array5.shape, dtype = array5.dtype)
print(array6)


Zeroes
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]]


In [28]:
#Arrays Predefinidos
lista2 = [[1,2,3],[4,5,6]]

# ones: Inicializa con 1
print("Ones")
array7 = np.ones((3,3), dtype = int)
print(array7)

array8 = np.ones_like(lista2)
print(array8)

array9 = np.ones(shape=array8.shape, dtype = array8.dtype)
print(array9)

Ones
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]]


In [31]:
# Full: inicializa con un valor pasado como parametro (en vez de zeros u ones)
lista2 = [[1,2,3],[4,5,6]]

print("Full")
array10 = np.full((3,3), 4 , dtype = int)
print(array10)

array11 = np.full_like(lista2, 6)
print(array11)

array12 = np.full(shape=array11.shape, fill_value=5 ,dtype = array11.dtype)
print(array12)

Full
[[4 4 4]
 [4 4 4]
 [4 4 4]]
[[6 6 6]
 [6 6 6]]
[[5 5 5]
 [5 5 5]]


In [37]:
#Aleatorios
#Distibucion Uniforme
print("Dist. Uniforme\n")
print("random.rand") #Distribucion Uniforme pseudo aleatoria, entre 0 y 1
array13 = np.random.rand(3,2)
print(array13)

print("random.uniform") #Distribucion Uniforme pseudo aleatoria, entre TOPES indicados del tipo [inicio,fin)
array14 = np.random.uniform(0,1,6).reshape(3,2)
print(array14)

Dist. Uniforme

random.rand
[[0.08923072 0.49350717]
 [0.258698   0.16754291]
 [0.41165723 0.81819827]]
random.uniform
[[0.37488888 0.21550508]
 [0.41909269 0.9366773 ]
 [0.92780174 0.02294298]]


In [39]:
#Aleatorios
#Distibucion Normal o GAUSSSIANA (camapana de Gauss)
print("Dist. Normal\n")
print("random.rand") #Distribucion NORMAL pseudo aleatoria, entre 0 y 1
array15 = np.random.randn(3,2)
print(array15)

print("random.uniform") #Distribucion NORMAL pseudo aleatoria, SCALE(2do Parametro) es la desviacion estandard de la distribucion normal.
array16 = np.random.normal(0,1,6).reshape(3,2)
print(array16)

Dist. Normal

random.rand
[[-1.02685458 -0.19706527]
 [-0.49093382  0.11645953]
 [ 1.18216276  0.7166979 ]]
random.uniform
[[-0.87054293 -0.14541467]
 [-0.17216125 -0.61189362]
 [-0.06625919  0.60212916]]


In [129]:
# DESDE UN ARCHIVO
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=object, usecols=[0,1,2,3])

print(iris_1d[:3])

[[b'5.1' b'3.5' b'1.4' b'0.2']
 [b'4.9' b'3.0' b'1.4' b'0.2']
 [b'4.7' b'3.2' b'1.3' b'0.2']]


TAMAÑO

In [97]:
#Shape (tamaño de las dimensiones)
a = np.arange(1,10)
print(a)
print(a.shape)

#REshape
a = np.arange(1,10)
print(a.reshape(3,3)) #no modifica la original
print(a.reshape(3,3).shape) 
#si a reshape le paso -1 calcula solo el tamaño de esa dimension
print(a.reshape(3,-1).shape)

# el shape retorna una tupla que podemos descomponer para saber el tamanio de cada una de las dimensiones
# ejemplo: filas, columnas = a.shape()

[1 2 3 4 5 6 7 8 9]
(9,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
(3, 3)


SLICING

In [51]:
b = np.arange(9).reshape(3,3)
print(b)

print("1 - \n", b[1,2])
print("2 - \n", b[0,:])
print("3 - \n", b[:,1])
print("4 - \n", b[:,1:])
print("5 - \n", b[0:2,0:2])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
1 - 
 5
2 - 
 [0 1 2]
3 - 
 [1 4 7]
4 - 
 [[1 2]
 [4 5]
 [7 8]]
5 - 
 [[0 1]
 [3 4]]


COPIADO

Si hago una asignacion normal, no copio el array, sino la referencia al mismo.

In [55]:
print("Copy")
#Referencia
a1 = np.array([2,4,6])
a2 = a1
a1[0] = 0
print(a1)
print(a2,"\n")

#Valor con Funcion Copy
a1 = np.array([2,4,6])
a2 = a1.copy()
a1[0] = 0
print(a1)
print(a2)

Copy
[0 4 6]
[0 4 6] 

[0 4 6]
[2 4 6]


OPERACIONES

In [63]:
#Suma y Resta Escalar: No modifica la Original
print("Suma Escalar")
a = np.array([1,2,3])
print(a+1)
b = np.ones(3, dtype=int) 
print(a+b)

print("Resta Escalar")
a = np.array([1,2,3])
print(a-1)
b = np.ones(3, dtype=int) 
print(a-b)

# Las operaciones de:
# -------------------

# producto escalar
# division escalar
# division entera escalar
# resto escalar
# potencia escalar

# SON ANALOGAS A LA SUMA Y RESTA ESCALAR

Suma Escalar
[2 3 4]
[2 3 4]
Resta Escalar
[0 1 2]
[0 1 2]


ESTADISTICA

In [81]:
a = np.arange(0,101)
print(a)

print("Media")
print(a.mean())
print(np.mean(a))

print("Mediana")
print(np.median(a))

print("Desviacion STD")
print(a.std())
print(np.std(a))

print("Percentiles")
print(np.percentile(a,90))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]
Media
50.0
50.0
Mediana
50.0
Desviacion STD
29.154759474226502
29.154759474226502
Percentiles
90.0


OTRAS FUNCIONES

In [89]:
a = np.arange(4)
b = np.arange(1,5)

#Exponencial
print("exponencial")
print(np.exp(a))

#Logaritmo
print("logaritmo")
print(np.log(b))

#Raiz Cuadrada
print("Raiz Cuadrada")
print(np.sqrt(a))

#Comparacion
print("Comparaciones con resultado booleano")
print(np.greater(a,b))
print(np.greater_equal(a,b))
print(np.less(a,b))
print(np.less_equal(a,b))
print(np.equal(a,b))
print(np.not_equal(a,b))

exponencial
[ 1.          2.71828183  7.3890561  20.08553692]
logaritmo
[0.         0.69314718 1.09861229 1.38629436]
Raiz Cuadrada
[0.         1.         1.41421356 1.73205081]
Comparaciones con resultado booleano
[False False False False]
[False False False False]
[ True  True  True  True]
[ True  True  True  True]
[False False False False]
[ True  True  True  True]


MASCARAS Y FILTRO (FILTRADO)

In [92]:
a = np.arange(0,20).reshape(2,10)
print(a)
#Mascaras
print("Mascaras")
mascara = ((a%2) == 0)
#resultado booleano de aplicar la mascara en el array
print(mascara)

#Filtro el array con la mascara
print(a[mascara])



[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[ True False  True False  True False  True False  True False]
 [ True False  True False  True False  True False  True False]]
[ 0  2  4  6  8 10 12 14 16 18]


In [98]:
#Filtro where
print("Where")
a = np.array([0,1,2,3,4,5,6,7,8,9])
#np.where(condicion, valor por true, valor por false)
out = np.where(a % 2 != 0,-1,a)

print(a)
print(out)

Where
[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


CONCATENACION APILADO

In [103]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

#Apilado VERTICAL
print(a)
print(b)
print()
print(np.concatenate([a,b], axis=0)) #con axis CERO concateno en COLUMNAS, es decir, VERTICALMENTE. Apilo arriba/abajo.
print()
print(np.vstack([a,b]))
print()
print(np.r_[a,b])
print()
print(np.vstack([a,b]).shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]

(4, 5)


In [104]:
#Apilado HORIZONTAL
print()
print(np.concatenate([a,b], axis=1)) #con axis UNO concateno en FILAS, es decir, HORIZONTALMENTE. Apilo izquierda/derecha.
print()
print(np.hstack([a,b]))
print()
print(np.c_[a,b])
print()
print(np.hstack([a,b]).shape)


[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]

(2, 10)


OTRAS FUNCIONES

In [8]:
a = np.array([1,2,3])
#REPEAT: Repite CADA elemento del array la cantidad de veces indicada.
#TILE: Repite la cantidad de elementos seleccionados a partir del final, lo repite la cantidad indicada.
print(np.concatenate([np.repeat(a,3),np.tile(a,3)], axis=0))

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [11]:
data = np.ones((1, 3, 1, 2))
print(data.shape)
#BORRAR DIMENSIONES DE TAMANIO 1
print(data)
print()
print(np.squeeze(data).shape)
print(np.squeeze(data))

(1, 3, 1, 2)
[[[[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]]]

(3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [115]:
#INTERSECCION 1D
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(np.intersect1d(a,b)) #devuelve los elementos que estan en ambos arrays, pero sin repetirlos

#DIFERENCIA
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

print(np.setdiff1d(a,b)) # devuelve los elementos que estan en el primer array y no en el segundo

# UNION
print(np.union1d(a,b)) #devuelve la union de ambos arrays pero sin repetir los que estan en ambos conjuntos.

# XOR: Devuelve los elementos que estan en cada array pero que no esten en AMBOS. Recordar que el XOR se vuelve FALSE cuando ambos operandos son TRUE.
print(np.setxor1d(a,b))

[2 4]
[1 2 3 4]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 6 7 8 9]


In [117]:
# BUSQUEDA DE ELEMENTOS DE UN ARRAY EN OTRO
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

print(np.in1d(a,b)) #devuelve las ocurrencias en formato BOOLEANO, por ende, lo puedo usar como mascara para filtrar y consultar los elementos.
#lo puedo usar como mascara
print(a[np.in1d(a,b)])

[False False False False  True]
[5]


In [126]:
# FUNCIONES APLICADAS A CADA ELEMENTO
def maxx(x, y):
    if x >= y:
        return x
    else:
        return y

#redefino la funcion como vertorizable, es decir, que se aplique individualmente a los elementos de los arrays
pair_max = np.vectorize(maxx, otypes=[int])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

print(pair_max(a,b))
#va a llamar a la funcion MAXX tantas veces como elementos tengan los arrays. Lo hace elemento a elemento. Numpy hace la descomposicion de manera automatica.

def par(x):
    if (x%2)==0:
        return -1
    else:
        return x
       

parv = np.vectorize(par, otypes=[int])

a = np.array([5, 6, 7, 8, 9, 10, 11, 12])

print(parv(a))

[6 7 9 8 9 7 5]
[ 5 -1  7 -1  9 -1 11 -1]


FUNCIONES LOGICAS

In [127]:
# np.logical_and(condiciones)
# np.logical_not(condiciones)
# np.logical_or(condiciones)
# np.logical_xor(condiciones)

<ufunc 'logical_or'>

ITERACION

In [1]:
#nditer ==> Sirve para iterar de forma eficientes CADA elemento de un array numpy, puede tener mas de una dimension. Suele utilizarse en un FOR.
import numpy as np

matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

for elemento in np.nditer(matriz):
    print(elemento)

1
2
3
4
5
6
7
8
9


In [2]:
#np.fromiter() ==> Recibe un iterable (lista, array, generador, etc). Crea un array nuevo a partir del iterable.
import numpy as np

iterador = range(5) #generador iterable
arr = np.fromiter(iterador, dtype=int)

print(arr)

[0 1 2 3 4]


In [8]:
import numpy as np

array6 = np.array([1,2,3,4,5])

#retorna un BOOL
def es_impar(x):
    return x % 2 != 0

#from el for retorna un GENERADOR DE BOOLEANOS
#el FROMITER toma el generador y crea un ARRAY DE BOOLEANOS
filtro = np.fromiter((es_impar(x) for x in array6), dtype=bool)
print(filtro)
#ambos pasos se podrian resolver con un FILTRO o MASCARA
print(array6 % 2 != 0)
print(array6[filtro])
print(array6[np.fromiter((es_impar(x) for x in array6), dtype=bool)])

[ True False  True False  True]
[ True False  True False  True]
[1 3 5]
[1 3 5]
